"""Compare the base model and the fine-tuned model on held-out questions.

For each example in the eval file it reports:
- answer loss: mean per-token NLL of the reference answer (lower is better)
- the greedy answer generated by each model, side by side

    python evaluate.py --model outputs/qwen3-ft
    python evaluate.py --model outputs/qwen3-ft --base Qwen/Qwen3-0.6B --eval-data eval.jsonl

Models are loaded one at a time so both don't have to fit in VRAM together.
"""
import argparse
import gc
import json
import statistics
import sys
from pathlib import Path

import torch

from data_utils import load_conversations
from inference import DEFAULT_BASE_MODEL, ChatModel, GenerationParams


def base_model_of(model_path):
    """Read the base model id that train.py recorded, if any."""
    info = Path(model_path) / "run_info.json"
    if info.is_file():
        return json.loads(info.read_text())["base_model"]
    return DEFAULT_BASE_MODEL


def run_model(model_path, conversations, params):
    chat = ChatModel.load(model_path)
    results = []
    for messages in conversations:
        prompt, reference = messages[:-1], messages[-1]["content"]
        results.append({
            "loss": chat.completion_loss(prompt, reference),
            "answer": chat.generate(prompt, params),
        })
    del chat
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    return results


def render_report(conversations, base_name, base, tuned_name, tuned):
    base_mean = statistics.mean(r["loss"] for r in base)
    tuned_mean = statistics.mean(r["loss"] for r in tuned)
    lines = [
        "# Evaluation report",
        "",
        "| Model | Mean answer loss (lower is better) |",
        "|---|---|",
        f"| base: `{base_name}` | {base_mean:.4f} |",
        f"| fine-tuned: `{tuned_name}` | {tuned_mean:.4f} |",
        "",
    ]
    for i, (messages, b, t) in enumerate(zip(conversations, base, tuned), start=1):
        lines += [
            f"## {i}. {messages[-2]['content']}",
            "",
            f"**Reference:** {messages[-1]['content']}",
            "",
            f"**Base** (loss {b['loss']:.3f}):\n\n{b['answer']}",
            "",
            f"**Fine-tuned** (loss {t['loss']:.3f}):\n\n{t['answer']}",
            "",
        ]
    return "\n".join(lines), base_mean, tuned_mean


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--model", default="outputs/qwen3-ft", help="fine-tuned model or adapter dir")
    p.add_argument("--base", default=None, help="base model (default: read from run_info.json)")
    p.add_argument("--eval-data", default="eval.jsonl")
    p.add_argument("--report", default=None, help="markdown report path (default: <model>/eval_report.md)")
    p.add_argument("--max-new-tokens", type=int, default=256)
    args = p.parse_args(argv)

    base_path = args.base or base_model_of(args.model)
    report_path = Path(args.report or Path(args.model) / "eval_report.md")
    conversations = load_conversations(args.eval_data)
    params = GenerationParams(temperature=0.0, max_new_tokens=args.max_new_tokens)  # greedy: reproducible

    print(f"evaluating base model {base_path} on {len(conversations)} examples ...")
    base = run_model(base_path, conversations, params)
    print(f"evaluating fine-tuned model {args.model} ...")
    tuned = run_model(args.model, conversations, params)

    report, base_mean, tuned_mean = render_report(conversations, base_path, base, args.model, tuned)
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(report, encoding="utf-8")

    print(f"\nmean answer loss  base: {base_mean:.4f}  fine-tuned: {tuned_mean:.4f}")
    print(f"report written to {report_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
